### ISSUE TITLE
Уведомление о компрометации реквизитов доступа к базам данных и внешним системам

### ISSUE THREAD

**Issue by antonydevanchi** [LegendaryZer0/yanaosharing#1]
Добрый день.

Стоит зачистить.

https://github.com/LegendaryZer0/yanaosharing/blob/a52c1d88bdff5d7c9e2ebda2ffd7715c3d5eb6c3/src/main/resources/application.properties#L35

Напомню, что удаление через коммит не удаляет из истории. 
Имеет смысл удалить репозиторий.

На будущее советую хранить переменные конфигурации в файле `.env` и использовать файл `.gitignore`.

Всех благ.

**Comment by LegendaryZer0** [comment]
Добрый день, данные properties уже устаревшие, поэтому, думаю, удалять их особого смысла нет, базу мы успешно сменили, спасибо за указание. Я закрою issue через 3 дня, если претензий больше не появится
